version: '3.4'

services:
  lerna:
    image: lerna
    build:
      context: node_modules/lerna
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
